### ISSUE TITLE
New attribute-function-interpolator does not work with "complex" attribute names

### ISSUE THREAD

**Issue by cayetanobv** [gtorodelvalle/fiware-device-simulator#170]
Hi @gtorodelvalle ,

New attribute-function-interpolator does not work properly with "complex" attribute names. 

Example 1:
```
"attribute-function-interpolator(${{camino-nuevo-01}{___Consumo_ModBus__energía_acumulada_activa_}} + ${{camino-nuevo-01}{___Consumo_activo_instantáneo__R+S+T_}})"
```

Example 2:
```
"attribute-function-interpolator(function add(a, b) { return a + b; }; add(${{camino-nuevo-01}{___Consumo_ModBus__energía_acumulada_activa_}},${{camino-nuevo-01}{___Consumo_activo_instantáneo__R+S+T_}});)"
```

Thanks!

**Comment by gtorodelvalle** [comment]
Hi @cayetanobv ! The issue does not seem to be related to the `attribute-function-interpolator` but to the Context Broker. I just saw that if I try to add an attribute such as `___Consumo_ModBus__energía_acumulada_activa_` to an entity, it does create it but it does not set the passed value. This works fine if the starting `_` is limited to only 1.

I am currently checking it with the Orion Context Broker team and I will be back to you ASAP ;)

**Comment by cayetanobv** [comment]
Hi @gtorodelvalle ! I think Orion Context Broker works fine with this kind of names (IoT Portal does not work in all cases); we have this active attribute working fine now (it is justa an example, but it works well):

```
{
               "name": "___Consumo_activo_instantáneo__R+S+T_",
               "type": "Number",
               "value": "time-random-linear-interpolator([[0,random(10.799999999999999,12.6)],[7,random(13.5,14.4)],[8,random(0.18,0.36)],[19.999,random(0.18,0.36)],[20,random(13.5,14.4)],[24,random(13.5,14.4)]])",
               "metadata": [
                  {
                     "name": "dateUpdated",
                     "type": "DateTime",
                     "value": "date-increment-interpolator({\"origin\": \"now\", \"increment\": 0})"
                  },
                  {
                     "name": "TimeInstant",
                     "type": "DateTime",
                     "value": "date-increment-interpolator({\"origin\": \"now\", \"increment\": 0})"
                  }
               ]
            }
```

**Comment by gtorodelvalle** [comment]
Not for me... :p At least using NGSI v1... If I request a queryContext after updateContext of an entity with an attribute starting with more than 1 starting `_` (such as `__Hola`), I get something such as this:

```
          {
            "name": "",
            "type": "Number",
            "value": "0.7",
            "metadatas": [
              {
                "name": "ID",
                "type": "string",
                "value": "Hola"
              }
            ]
          }
``` 
which I would say is the expected behaviour :) , but currently confirming it with our Orion Context Broker team.

**Comment by gtorodelvalle** [comment]
The Orion Context Broker team has just confirmed that it is a bug and it has been filed with maximum priority... ;) I'll come back to you once it is solved and properly deployed in the Integrators Environment... :)

**Comment by cayetanobv** [comment]
Ok, great @gtorodelvalle ! It is not a bug of this interpolator, but we can keep open this issue until this bug is fixed in Orion Context Broker.

**Comment by gtorodelvalle** [comment]
In fact, I just found the issue in the Orion Context Broker repository where this issue is being dealt with: https://github.com/telefonicaid/fiware-orion/issues/2453

**Comment by gtorodelvalle** [comment]
The Geographica and the Telefónica teams have just confirmed that for the use case where this issue arose, multiple `_` at the beginning of attributes names are no longer used so this issue can safely be closed... ;)

On other hand, this is the fix which has just landed in the Orion Context Broker code recently to solve the issue: https://github.com/telefonicaid/fiware-orion/pull/2616

@cayetanobv , could you close the issue if you are fine with the current solution/situation? :)

**Comment by cayetanobv** [comment]
Ok @gtorodelvalle . Closing issue...
