### ISSUE TITLE
syntax for configuration make it more coherent

### ISSUE THREAD

**Issue by jmcanterafonseca** [gtorodelvalle/fiware-device-simulator#19]
instead of using active --> `dynamic_attrs`
instead of `entity_name` --> `entity_id`

consider using `camelCase` instead of underscore

**Comment by gtorodelvalle** [comment]
There is a reason for that nomenclature and it is the fact that it is the one used by the IoT Agents, and I did not want the users of the simulator "to learn" an additional nomenclature. I'll be glad to update the nomenclature of the simulator once the IoT Agents do... :)

Please, refer to telefonicaid/iotagent-node-lib#437 for further information.
