### ISSUE TITLE
Omitted type when requesting an entity may produced unexpected attribute values

### ISSUE THREAD

**Issue by javimudi** [gtorodelvalle/fiware-device-simulator#200]
Hi, @gtorodelvalle ,

When an entity with similar attributes to a pre-existent one, but different type, is simulated, attributes accessed at the attributteFunctionInterpolator may belong to the unwanted entity.

Including the entity type when requesting the attribute probably might solve the thing.

Regards

**Comment by gtorodelvalle** [comment]
Hi @javimudi , would you be so kind to check that release 7.7.0 implements the possibility to specified the entity type in the attribute-function-interpolator successfully and once you do close this issue, please :)

**Comment by javimudi** [comment]
Checking...

**Comment by javimudi** [comment]
Everything seems to be working fine. I'm closing this issue.

Thx
