### ISSUE TITLE
Access to other attributes within a function interpolator

### ISSUE THREAD

**Issue by javimudi** [gtorodelvalle/fiware-device-simulator#217]
Hi, @gtorodelvalle 

In order to make realistic simulations some attributes might depend on other attributes at the very same data triggering. We can now access to just generated values querying the context broker with the '${{}}' syntax, but this is provoking delayed values for calculated attributes.

¿Any idea about how this can be implemented?

Regards

**Comment by gtorodelvalle** [comment]
Hi @javimudi , I hope the new global state variables included in the https://github.com/gtorodelvalle/fiware-device-simulator/releases/tag/7.11.0 release is aligned with your suggestion... :)
I would appreciate if you could give me feedback on it and if you are fine with it, please proceed to close the current issue... ;)
Thank you very much for your contribution!

**Comment by javimudi** [comment]
Hi,

Everything works as expected.

Thanks!
