### ISSUE TITLE
Simulator emits end when TokenNotAvailable error is raised

### ISSUE THREAD

**Issue by cayetanobv** [gtorodelvalle/fiware-device-simulator#74]
Hi team,

When a TokenNotAvailable error is raised (i.e. due to maintenance tasks) simulator emits an end signal and all jobs are canceled. Could it be a good idea to put a new parameter setting a timeout (or number of attemps with a time interval)?

Thanks for all your great work!

**Comment by gtorodelvalle** [comment]
Hi @cayetanobv , it looks good to me... ;) I'll include it ASAP... :) Thanks!

**Comment by cayetanobv** [comment]
Thanks @gtorodelvalle
