### ISSUE TITLE
Schedule: range values are not supported (nor value list)

### ISSUE THREAD

**Issue by cayetanobv** [gtorodelvalle/fiware-device-simulator#94]
Hi team,

When you are trying to use range values in shedules simulator raise a SimulationConfigurationNotValid error. This is important to avoid send values when a parking is close (i.e. between 21:00 and 7:00 - closed hours -  simulator does nothing avoiding overhead).

Example (config and error raised): 
- `"schedule": "0 0 6-22 * * *"`
- `{"time":"2016-09-25T08:38:40.705Z","lvl":"ERROR","msg":"error event: { error: \n   { [SimulationConfigurationNotValid: The entity configuration information at array index position 0 includes an invalid schedule: '0 0 6-22 * * *']\n     name: 'SimulationConfigurationNotValid',\n     message: 'The entity configuration information at array index position 0 includes an invalid schedule: \\'0 0 6-22 * * *\\'' } }"}`

I was reviewing regular expression in validateScuedule function and this feature is not supported:

``` javascript
function validateSchedule(schedule, parentType, parentIndex, callback) {
  var err;
  if (schedule && !/(^once$|^(\*\/[0-9]+\s+|\*\s+|[0-9]+\s+){4,5}(\*\/[0-9]+|\*|[0-9]))/g.test(schedule)) {
    err = new fdsErrors.SimulationConfigurationNotValid('The ' + parentType + ' configuration information ' +
      'at array index position ' + parentIndex + ' includes an invalid schedule: \'' + schedule + '\'');
  }
  callback(err);
}
```

It is also not supported to pass a value list in schedulers like "0 0 6,22 \* \* *" (I reviewed cron-schedule docs and I am not sure this is supported by library although it is a classical Unix feature in crontabs). This feature is important because an example like this: 
- a parking (at parking entity level) sends two signals a day: when open at 6:00 and when close at 22:00. At parking spot level simulations for status (occupied or free) can be much more frequently (i.e. each 15 minutes).

Thanks!

**Comment by cayetanobv** [comment]
Tested. It's working ok... so I'm going to close this isuue.

**Comment by gtorodelvalle** [comment]
HI @cayetanobv , it should be fixed in the new 7.0.1 release (https://github.com/gtorodelvalle/fiware-device-simulator/releases/tag/7.0.1) ;) Would you be so kind to check it out (remember than from release 7 on the `authentication.provider` is a mandatory property in the simulation configuration files... :)

**Comment by gtorodelvalle** [comment]
Hi @cayetanobv , just checking if this issue can be closed... :) Just not to keep open issues if they are already solved... :) Thanks!

**Comment by cayetanobv** [comment]
Sorry @gtorodelvalle, this issue is tested... I forgot to close ;)
